### ISSUE TITLE
Мультиполя

### ISSUE THREAD

**Issue by jslby** [Elias-Black/Landing-CMS#1]
Здравствуйте, Илья!
Ваша CMS просто идеальна, и проста. Это именно то, что я не раз начинал писать, бросал из-за горящих сроков и откладывал в долгий ящик.
Единственное, чего очень не хватает - это реализации мультиполей. Это полезно, когда например на лендинге галерея изображений, или список партнеров, или например каталог продукции.
Это дополнение очень сильно облегчит мне жизнь, поэтому я даже готов отблагодарить финансово.
Так же было бы круто, среди типов полей видеть селекты и выбор файла.
Если что, пишите на почту: me@jslby.ru

**Comment by Elias-Black** [comment]
Добрый день Ярослав!

Огромное спасибо за такой отзыв! Сам искал много лет что-то подобное, но не смог найти то, что устраивало бы, и пришлось написать самому :-) Понимая, что я такой не один, решил выложить в открытый доступ.
К сожалению, не всегда хватает времени на развитие проекта, но как только появляется мотивация и время, сразу добавляю новые функции.
На днях добавил в dev-ветку новый тип поля - Color Picker. Теперь можно легко задавать цвета.
В следующий раз планирую добавить поле для загрузки файлов.

Все планы по развитию можно прочесть в Readme в разделе To do... Добавление групп полей планировал с самого создания CMS, но только после релиза первой стабильной версии, до этого нужно улучшить безопасность и упростить установку (убрать нужду выставлять 403 редирект).

Про группы полей, в таком виде, в каком предлагаете вы, раньше не задумывался, хотя в любом случае пришёл бы к такой мысли, т.к. по-другому реализовать и не получилось бы и было бы даже глупо. Вообще идея очень хорошая, но требует обдумывания. Огромное спасибо за ценное предложение!

P.S: Для уточнения идеи реализации свяжусь по email.

**Comment by Elias-Black** [comment]
Привет!

Работа уже идёт, в [dev-ветке](https://github.com/Elias-Black/Landing-CMS/tree/dev) уже есть новый функционал.

Если кратко, добавлено:
- Группы полей;
- Редактирование полей (смена Родителя, Типа, Алиаса, Имени и Описания);
- Сортировка полей (можно ставить одно поле выше/ниже другого, что отразится и в админке, и в коде);
- Скрытие/Раскрытие содержимого Групп с запоминанием состояния;
- Много мелких, но очень важных правок.

Выглядит хорошо, работать удобно и в админке и в коде самого лендинга.
![001](https://cloud.githubusercontent.com/assets/25124661/26757139/533cb88c-48cc-11e7-96fb-9a57b48963f1.png)

Совместимости баз данных со старой версией не будет, но код самого лендинга менять не придётся, просто нужно будет завести в админке старые поля с таким же контентом.

Вложенность групп неограниченная.
Обращаться к элементам и перебирать элементы групп можно как в обычных многомерных массивах:
1. Вывод конкретного элемента в коде
```
<p>
   <?=$get['main_group']['item1'];?>
</p>
```
2. Вывод всех элементов группы списком
```
<?php foreach($get['main_group'] as $name => $item): ?>
   <ul>
      <li><b><?=$name;?>:</b> <?=$item;?>;</li>
   </ul>
<?php endforeach; ?>
```

Содержимое групп можно сворачивать/разворачивать, состояние запоминается и при открытии админки даже с другого компьютера, группы будут открыты/закрыты в соответствии с предыдущими действиями.

Также добавил редактирование любого элемента (с возможностью сменить Родителя, Тип, Алиас, Название и описание).

И изменение порядка элементов и групп. Теперь поля можно поднимать и опускать меняя порядок и в админке и на фронте.

Сделал ещё кучу мелких, но важных правок.

В планах, добавить копирование элементов и групп вместе со всем содержимым, и многое многое другое... Но уже в следующих релизах, это и так получается очень большим :-)

На данный момент почти всё реализовано, осталось только заверстать иконки и всё окончательно протестировать.

Issue закрываю т.к. считаю завершённым.
