### ISSUE TITLE
Deployment for no root directory

### ISSUE THREAD

**Issue by veggigit** [Elias-Black/Landing-CMS#2]
Hello, thx for this app. the issue is.... I cant install this cms. Then change all permissions, go to /cms pannel and error 404. My url project is http://localhost:44333/www/test-cms/ When i want to go to http://localhost:44333/www/test-cms/ the app  redirect to http://localhost:44333/cms/
Thx for u help.

PD: This issue also happens in live server.

**Comment by Elias-Black** [comment]
Hello!
This bug has been fixed in the DEV branch (not for use in production). Unfortunately, I do not have enough time now to finish the work on the DEV branch. As soon as the time appears, everything will be finished and appear in the MASTER branch.

Thank you!

**Comment by veggigit** [comment]
ok, thx u. I'll wait that version.

**Comment by Elias-Black** [comment]
New version in master! That contain more cool features beside this setting.
If you want to use Landing CMS in not root directory you need to change the constant `SITE_FOLDER` in `cms/_classes/utils.class.php`
If you address is `example.com/landing/` the constant will be `/landing/`
