### ISSUE TITLE
Не могу поставить под Опенсервер

### ISSUE THREAD

**Issue by trolllik** [Elias-Black/Landing-CMS#3]
Развернул, При обращении к инсталл все доступы есть, 
добавил руками
![image](https://user-images.githubusercontent.com/13703618/30260718-b276d1b8-96d1-11e7-8a46-8cedd4a6fad9.png)

при переходе к cms вот такая штука
![image](https://user-images.githubusercontent.com/13703618/30260733-cf179096-96d1-11e7-95fc-2aeabc271774.png)
Хотя по идее должно быть задание пароля. ставил на php  5.6, хотя пробовал и 5.2 результат тот же. Не скажите где не досмотрел?

**Comment by Elias-Black** [comment]
Поставил Open Server (до этого на винде тестил в окружении простого Denwer), ошибку воспроизвести не удалось.

Ещё актуально, исправить не удалось?
Если актуально, то не могли бы вы:
1. В файле cms/_classes/user.class.php после 35ой строки добавить следующие две:
```
		var_dump($db_pwd);
		die;
```
и ответить в этом тикете что вывелось на экран.
2. Проверить нет ли какого-нибудь символа/строки в файле cms/_db/password.php (лучше приложить его к комментарию).

Спасибо за обращение, надеюсь скоро разберёмся!

**Comment by trolllik** [comment]
![image](https://user-images.githubusercontent.com/13703618/30277606-0596efe2-9711-11e7-91a3-98c708657a99.png)

не добавляется даже если в зип сжать, но он пуст

**Comment by trolllik** [comment]
Странно, я не понял ка но заработало. Скажите а вопрос такой, как подвесить свой ленд, и править контент, контент конечно лучше б в виде бв=азы(  или таблицы) это сущности, скажем попапы сос своими строками

**Comment by Elias-Black** [comment]
Рад, что всё заработало, надеюсь, смогу поправить в следующих релизах причину, по которой сразу всё не сработало.

Описание, как работать в вашем коде, с контентом, который вы создаёте в админке, есть на главной странице репозитория https://github.com/Elias-Black/Landing-CMS (там выводится файл README).

Также, примером может послужить файл index.php в корневой директории.
