### ISSUE TITLE
CMS не устанавливается без пдавления ошибок

### ISSUE THREAD

**Issue by drkrol** [Elias-Black/Landing-CMS#4]
1.
` Warning: file_get_contents(E:\openserver\OpenServer\domains\shpagin.time/cms/_db/public.php): failed to open stream: No such file or directory in E:\openserver\OpenServer\domains\shpagin.time\web\index.php on line 24`

2.
```
Warning: file_get_contents(E:\openserver\OpenServer\domains\shpagin.time/cms/_db/password.php): failed to open stream: No such file or directory in E:\openserver\OpenServer\domains\shpagin.time\cms\_classes\db.class.php on line 112

Warning: Cannot modify header information - headers already sent by (output started at E:\openserver\OpenServer\domains\shpagin.time\cms\_classes\db.class.php:112) in E:\openserver\OpenServer\domains\shpagin.time\cms\_classes\utils.class.php on line 37
```

**Comment by drkrol** [comment]
Вы русский, слава богу))) Поставил openserver, а он мне вот такую ошибку выдаёт. Как исправить?

**Comment by drkrol** [comment]
первая ошибка при открытии страницы index.php, а две вторые на странице cms/index.php

**Comment by Elias-Black** [comment]
Приветствую вас) с OpenServer начались проблемы после того, как я сделал процесс установки проще, для большинства пользователей.

Раньше, в папке `cms/_db` находилось 3 файла баз данных: приватная (внутренняя), публичная (внешняя) и пароль. При установке приходилось ставить права на каждый файл вручную.

Сейчас этих файлов в папке нет, и при установке нужно поставить разрешающие (создавать, изменять и просматривать) права только на саму папку `cms/_db`

OpenServer как я заметил, создаёт папки для сайтов с минимальными правами, только на чтение. Вам нужно выставить ращрешающие права на папку `cms/_db`, а возможно и на папки верхнего уровня.

Возможно, нужно будет перезапустить OpenServer.

Тестировал Landing CMS в OpenServer и всё идеально заработало, как только поставил нужные права.

P.S.: Изменил процесс установки не только что бы приходилось права ставить не на 3 файла, а на  1 папку, но и потому, что в будущих релизах планируется в этой папке иметь куда больше трёх файлов.

P.P.S.: Надеюсь, мой комментарий помог, если так, то ответье пожалуйста здесь)

**Comment by drkrol** [comment]
Я вот себя сейчас очень тупым ощущаю. Будто, я что-то не то делаю... Перекачал файлы, но ситуация никак не поменялась.
Вот я залил их на хостинг http://a.farber.ml/
Может быть какая-то особенность в установке есть, которую я не знаю?

**Comment by Elias-Black** [comment]
А какие права стоят на папке `cms/_db`? Должно быть 777 или то, что позволит PHP процессу создавать, редактировать и просматривать файлы внутри данной директории.

**Comment by drkrol** [comment]
В том-то и дело, что права 777, иными словами drwxrwxrwx

**Comment by drkrol** [comment]
Хост: s25.webhost1.ru
Логин: u215184_1
Пароль: 123456

Не думаю, что нас еще кто-то смотрит)

**Comment by Elias-Black** [comment]
Доступ к хостингу получить не удалось, там вроде по IP не пускает, но всё равно, не одобряю такой смелый ход и рекомендую срочно сменить логин/пароль на своём аккануте (тем более, что на нём вроде бы и production сайт лежит).

Запустить CMS удалось http://a.farber.ml/cms/ (пароль 12 - тоже срочно смените!).

Проблема как я понял в том, что у вас не стоит подавления ошибок. PHP пытается открыть файл, а  его нет, и в обычной ситуации функция обращения к файлу просто возвращает FALSE, а ошибка пишется в лог, но сайт продолжает работать.

С вашей же настройкой PHP скрипт "падает" при попытке прочесть не существующий файл.

Варианты решения проблемы:

- Либо создать все 3 файла в ручную
- Либо включить подавление ошибок чтения несуществующих файлов
- Либо обернуть обращение к файлам в блок try-catch

Последний вариант, наверное, использую для фикса этой проблемы, в следующем релизе.

**Comment by Elias-Black** [comment]
Если что, вот иструкция, как удалось запустить:

- Заходим в админку http://a.farber.ml/cms/ но там видим только сообщение об ошибке чтения несуществующего файла;
- Тогда ручками вбиваем адрес страницы создания пароля http://a.farber.ml/cms/password и создаём пароль;
- Далее переходим в админку http://a.farber.ml/cms/ и логинемся;
- Теперь создаём какое-нибудь поле;
- Снова переходим на главную страницу админки http://a.farber.ml/cms/ и там сохраняем форму.

Как результат, все 3 файла созданы.

**Comment by drkrol** [comment]
Почему не пустило на ftp — я так и не понял. Этот ftp аккаунт снёс.
Сложный путь... Я бы не допёр) Благодарю, что помогли найти решение.
Сейчас буду сидеть, разбираться, как оно всё тут работает.

**Comment by Elias-Black** [comment]
Рад был помочь...
Будут вопросы - обращайтесь)

Email для связи: landingcms@yahoo.com (надо бы его в readme вписать :-) )

**Comment by drkrol** [comment]
Написал на почту.
