### ISSUE TITLE
ssrf and Any file read

### ISSUE THREAD

**Issue by blackjliuyun** [Elias-Black/Landing-CMS#7]
A SSRF vulnerability was discovered in landing-cms .here is a SSRF vulnerability that allows attackers to  read server sensitive information. via /assets/vendor/responsive_filemanager_9.12.1/filemanager/upload.php 
post: fldr=test11&url=file:///etc/passwd
<img width="1399" alt="wx20180912-184718 2x" src="https://user-images.githubusercontent.com/23147261/45420464-ce891f80-b6bc-11e8-8cc9-323cf31909fc.png">

<img width="1110" alt="wx20180912-185241 2x" src="https://user-images.githubusercontent.com/23147261/45420566-0bedad00-b6bd-11e8-80b0-147232c1b7eb.png">

and then cos would touch a file named fldr and the name of ssrf file

![wx20180912-185443](https://user-images.githubusercontent.com/23147261/45420665-540ccf80-b6bd-11e8-8bab-3483fc99d6f4.png)

so attackers can read server sensitive information
<img width="849" alt="wx20180912-185622 2x" src="https://user-images.githubusercontent.com/23147261/45420753-93d3b700-b6bd-11e8-8d51-5b4513b100c2.png">

**Comment by Elias-Black** [comment]
It's a good discover! Thank you for the job!

But responsive_filemanager is a injection. This is clearly stated in the Readme file (last part)...
The vendor of this is https://www.responsivefilemanager.com/

You can send your feedback to owner of this code :)
